name: RSpec

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.7.1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.7.0
      - name: Set up PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: "13"
          postgresql db: "bombeelu_ninja_test"
          postgresql user: postgres
          postgresql password: postgres
      - name: Install dependencies
        run: RAILS_ENV=test bin/setup
      - name: Run tests
        run: bundle exec rspec
